import type { Project, User } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Nitin Gadkari',
    avatarUrl: 'https://placehold.co/100x100.png',
    skills: ['Python', 'PyTorch', 'Natural Language Processing', 'Generative Models'],
  },
  {
    id: 'user-2',
    name: 'Ankur Warikoo',
    avatarUrl: 'https://placehold.co/100x100.png',
    skills: ['JavaScript', 'React', 'Node.js', 'System Design'],
  },
  {
    id: 'user-3',
    name: 'Sundar Pichai',
    avatarUrl: 'https://placehold.co/100x100.png',
    skills: ['C++', 'Unreal Engine', 'Computer Graphics', 'Game Physics'],
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Nitin Gadkari – “Innovation Overcomes All Roads”',
    description: 'A deep learning model to predict social connections and viral content spread, using graph neural networks.',
    field: 'Divination',
    tags: ['AI', 'hydrogen vehicles', 'Social Media', 'Predictive Analytics'],
    ownerId: 'user-1',
    teamIds: ['user-1', 'user-2'],
    isComplete: false,
    mainContent: 'India’s greatest projects didn’t begin with money — they began with courage. You don’t wait for the perfect time. You begin with what you have. I’ve seen highways built where there were none, and progress where there was resistance. The same applies to your ideas. If you have a half-finished plan, don’t abandon it. Revive it. Innovate it. And remember — sometimes the best roads are the ones you build yourself.\n\n— Nitin Gadkari, Minister of Road Transport & Highways',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'social network',
  },
  {
    id: 'proj-2',
    title: 'Steve Jobs – “The Dots Will Connect”',
    description: `💡 "What feels like a mess today may become your masterpiece tomorrow — don’t quit on your dots."

`,
    field: 'Potions',
    tags: ['Biochemistry', 'Synthetic Biology', 'CRISPR', 'Metabolic Engineering'],
    ownerId: 'user-2',
    teamIds: ['user-2'],
    isComplete: false,
    mainContent: 'Research paper draft. Includes gene sequences, protein folding simulations, and initial lab results on algae culture growth rates under modified conditions. Next steps involve testing oxygen output efficiency.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'underwater biology',
  },
  {
    id: 'proj-3',
    title: 'Sundar Pichai – “Ideas Need Patience, Not Perfection”',
    description: 'An exploration into quantum entanglement for instantaneous, secure data transfer between research labs.',
    field: 'Charms',
    tags: ['Quantum Computing', 'Cryptography', 'Qiskit', 'Hardware'],
    ownerId: 'user-3',
    teamIds: ['user-3', ],
    isComplete: false,
    mainContent: 'The most transformative ideas don’t emerge fully formed. They evolve — quietly, patiently, iteratively. Google itself began as a research project. What mattered wasn’t just brilliance, but belief. If your project feels incomplete, it doesn’t mean it’s unworthy. Keep nurturing it, brick by brick. Sometimes, the world catches up to your vision — not the other way around.\n\n— Sundar Pichai, CEO of Alphabet Inc.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'quantum computer',
  },
  {
    id: 'proj-4',
    title: 'Ancient Runes Translation Engine',
    description: 'A machine learning model to translate ancient and forgotten languages using transformer architecture and transfer learning.',
    field: 'Runes',
    tags: ['Machine Learning', 'NLP', 'TensorFlow', 'LLM'],
    ownerId: 'user-2',
    teamIds: ['user-2', 'user-1'],
    isComplete: false,
    mainContent: 'This project includes a scraped dataset of runic inscriptions and a partially trained BERT model. The model struggles with context and ambiguous symbols. The unfinished Jupyter notebook contains data preprocessing steps and model training code.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'ancient runes',
  },
  {
    id: 'proj-5',
    title: 'Automated Mandrake Re-potting System',
    description: 'A robotics project to design a system that can safely and automatically re-pot screaming Mandrakes when they mature.',
    field: 'Herbology',
    tags: ['Data Science', 'Robotics', 'Computer Vision', 'Pandas'],
    ownerId: 'user-3',
    teamIds: ['user-3'],
    isComplete: true,
    mainContent: 'The system uses a custom-trained YOLOv5 model to detect mandrake maturity based on leaf patterns. A robotic arm then performs the re-potting procedure. This vault contains the dataset, trained model weights, and control software.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'robotic arm plant',
  },
  {
    id: 'proj-6',
    title: 'The Goblet of Sorting',
    description: 'A web application that sorts new students into collaborative project groups based on their skills and project interests.',
    field: 'Transfiguration',
    tags: ['Software Dev', 'React', 'Firebase', 'Matching Algorithm'],
    ownerId: 'user-2',
    teamIds: ['user-2', 'user-3'],
    isComplete: false,
    mainContent: 'The frontend is built with Next.js and Tailwind CSS. The backend uses Firebase for authentication and data storage. The core matching algorithm is incomplete and needs refinement to handle complex skillsets and preferences.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'fantasy goblet',
  }
];
